export class PendingDataEntries {
  DPID: number;
  facilityID: number;
  categoryID: number;
  catName?: string;
  subcategoryID: number;
  subcatName?: string;
  Active?: boolean;
  isMandatory?: boolean;
  readingValue: number;
  unit: string;
  submissionDate: Date;
  status: string;
  month: string;
  dataEntryID: number;
  note: string;
  statusDate: Date;
  year: string;
  fileName: string;
  filePath: string;
  sendForApproval: boolean;
  tenantID: number;
  ghgEmission: number;
  reason: string;
  Status: string;
  blendType: string;
  blendID: number;
  blendPercent: number;
  refAmount: number;
  id:number;
  subCatName:string
  // cO2LeakagePerUnit: number;
  // capacity: number;
  // leakagePerOfCapacity: number;
  // airConnIDRef: string;
  numberOfExtinguisher: number;
  quantityOfCO2makeup: number;
  fireExtinguisherID: string;
  noOfVehicles: number;
  modeOfDE: string;
  modeofDEID: number;
  value: number;
  sourceName: string;
  sourceID: number;
  vehicleTypeID: number;
  avgPeoplePerTrip: string;
  totalnoOftripsPerVehicle: string;
  chargingPerc: string;
  typeID: number;
  typeName: string;
  electricityRegionName: string;
  electricityRegionID: number;
  calorificValue: number;
  ID:number;
  tablename:string;
  categoryId: number;
}